server:
  port: 10022
spring:
  profiles:
    active: dev
  application:
    name: wms
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: deleteFlag # 全局逻辑删除字段名
      logic-delete-value: UNIX_TIMESTAMP() # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0
