-- 送货员
CREATE TABLE IF NOT EXISTS deliveryman (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(100) NOT NULL COMMENT '名称',
  phone VARCHAR(30) NULL COMMENT '手机',
  tel VARCHAR(30) NULL COMMENT '座机',
  wechat VARCHAR(50) NULL COMMENT '微信号',
  address VARCHAR(255) NULL COMMENT '地址',
  scope TINYINT NOT NULL DEFAULT 0 COMMENT '适用范围：0-不限 1-入库 2-出库',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
  remark VARCHAR(255) NULL COMMENT '备注',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(64) NULL COMMENT '创建人',
  update_by VARCHAR(64) NULL COMMENT '更新人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='送货员';

CREATE INDEX idx_deliveryman_name ON deliveryman(name);
CREATE INDEX idx_deliveryman_scope ON deliveryman(scope);
