-- 出入库类型
CREATE TABLE IF NOT EXISTS io_type (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(100) NOT NULL COMMENT '类型名称',
  scope TINYINT NOT NULL DEFAULT 0 COMMENT '适用范围：0-不限 1-入库 2-出库',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(64) NULL COMMENT '创建人',
  update_by VARCHAR(64) NULL COMMENT '更新人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='出入库类型';

CREATE UNIQUE INDEX uk_io_type_name ON io_type(name, scope);
