-- 库存主表
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  product_id BIGINT NOT NULL COMMENT '商品ID',
  total_qty DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总库存数',
  location_ids VARCHAR(255) NULL COMMENT '货位IDs，逗号分隔',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(64) NULL COMMENT '创建人',
  update_by VARCHAR(64) NULL COMMENT '更新人',
  delete_flag BIGINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存主表';

CREATE UNIQUE INDEX uk_inventory_product ON inventory(product_id, delete_flag);
